
# Set up OpenAI API key.
OPENAI_API_KEY="your OPENAI_API_KEY "
# If you are using the API service provided by OpenAI, include the following line:
OPENAI_API_TYPE="openai"
# Set up You.com search API key.
YDC_API_KEY="your YDC_API_KEY"

